### ISSUE TITLE
README references files that do not exist

### ISSUE THREAD

**Issue by partytax** [ParkingReformNetwork/mandates-map#93]
In trying to build/run this project, I noticed that `parking_reform.R` and `app.R` don't exists. Looks like there's also a `Dockerfile` in the repo now, but didn't see a mention of that. 

Let me know which of these things are relevant and I'd love to submit a patch.

**Comment by bradbakermusic** [comment]
Yep the app.R file no longer exists. The shiny app lives within the map
folder and there is a server.R and ui.R file in there rather than just one
app.R file.

**Comment by Eric-Arellano** [comment]
Closed by https://github.com/ParkingReformNetwork/mandates-map/commit/b747c88a208b753cb354adc58eeabb19da616f60. Thanks for fixing this!
