### ISSUE TITLE
Dockerfile exposes port 3838, but shiny picks random container port to serve on

### ISSUE THREAD

**Issue by partytax** [ParkingReformNetwork/mandates-map#94]
Just talked with Tony and he said Dockerfile might be vestigial. If so, I guess we should remove it? I'm not familiar enough with this project to judge.

**Comment by bradbakermusic** [comment]
Hey Nathan,

The dockerfile is definitely vestigial at this point. Feel free to remove
it.

**Comment by Eric-Arellano** [comment]
Closed by https://github.com/ParkingReformNetwork/mandates-map/commit/b747c88a208b753cb354adc58eeabb19da616f60
